name: Deploy to Digital Ocean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via rsync
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts

          # Deploy each site
          rsync -avz --delete collector.cse135vrc.site/ $SERVER_USER@$SERVER_IP:/var/www/collector.cse135vrc.site/
          rsync -avz --delete reporting.cse135vrc.site/ $SERVER_USER@$SERVER_IP:/var/www/reporting.cse135vrc.site/
          rsync -avz --delete cse135vrc.site/ $SERVER_USER@$SERVER_IP:/var/www/cse135vrc.site/
          ssh $SERVER_USER@$SERVER_IP "sudo chown -R $SERVER_USER:$SERVER_USER /var/www/test.cse135vrc.site"
          rsync -avz --delete test.cse135vrc.site/ $SERVER_USER@$SERVER_IP:/var/www/test.cse135vrc.site/

          ssh $SERVER_USER@$SERVER_IP "chmod +x /var/www/cse135vrc.site/public_html/hw2/python/*.py"
          ssh $SERVER_USER@$SERVER_IP "chmod +x /var/www/cse135vrc.site/public_html/perl/*.pl"
          ssh $SERVER_USER@$SERVER_IP "chmod +x /var/www/cse135vrc.site/public_html/hw2/go/*.go"
          ssh $SERVER_USER@$SERVER_IP "chmod +x /var/www/cse135vrc.site/public_html/hw2/go/*.cgi"
